# 公共配置文件
# @author <a href="https://github.com/Azure12355">蔚蓝</a>
# @from 
spring:
  application:
    name: deep-forest
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deep_forest
    username: root
    password: 12345678
  # Redis 配置
  # todo 需替换配置，然后取消注释
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 大模型配置
  ai:
    openai:
      base-url: "https://ark.cn-beijing.volces.com/api"
      api-key: ${VOLCANO_API_KEY}
      chat:
        options:
          model: "deepseek-v3-241226"

#  ai:
#    openai:
#      base-url: "https://api.openai-hk.com" # gpt-4o
#      api-key: ${OPENAI_API_KEY} # gpt-4o
#      chat:
#        options:
#          model: "gpt-4o-mini"
#  ai:
#    openai:
#      api-key: ${ALIYUN_API_KEY}
#      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
#      chat:
#        options:
#          model: "deepseek-r1-distill-llama-70b"
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.weilanx.deepforest.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.weilanx.deepforest: debug
ark:
  ai:
    api-key: ${VOLCANO_API_KEY}
    base-url: "https://ark.cn-beijing.volces.com/api/v3/"
    model: "bot-20250412092028-d2c5z"