# 公共配置文件
# @author <a href="https://github.com/Azure12355">蔚蓝</a>
# @from 
spring:
  application:
    name: deep-forest
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # 大模型配置
  ai:
    openai:
      base-url: "https://ark.cn-beijing.volces.com/api"
      api-key: ${VOLCANO_API_KEY}
      chat:
        options:
          model: "deepseek-v3-241226"
  main:
    web-application-type: servlet

#  ai:
#    openai:
#      base-url: "https://api.openai-hk.com" # gpt-4o
#      api-key: ${OPENAI_API_KEY} # gpt-4o
#      chat:
#        options:
#          model: "gpt-4o-mini"
#  ai:
#    openai:
#      api-key: ${ALIYUN_API_KEY}
#      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
#      chat:
#        options:
#          model: "deepseek-r1-distill-llama-70b"
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.weilanx.deepforest: debug
ark:
  ai:
    api-key: ${VOLCANO_API_KEY}
    base-url: "https://ark.cn-beijing.volces.com/api/v3/"
    model: "bot-20250412092028-d2c5z"